version: "3.7"

services:

  ##### user database
  user_db:
    image: postgres
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: user
      POSTGRES_DATABASE: user
    ports:
      - 5444:5444

  ##### auth
  auth:
    image: grpc/auth-service:latest
    container_name: auth
    depends_on:
      - user
      - redis-master
    ports:
      - "9090:9090"
    restart: unless-stopped
    environment:
      PORT: 9090
      USER_SVC_ADDR: user:9091
      SECRET: rokgne
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      ENVIRONMENT: dev

  ##### user
  user:
    image: grpc/user-service:latest
    container_name: user
    ports:
      - "9091:9091"
    restart: unless-stopped
    environment:
      PORT: 9091
      DB_HOST: user_db
      DB_DEBUG: true
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: user
      DB_NAME: user
      ENVIRONMENT: dev

  ##### envoy-api
  envoy-api-dev:
    image: envoyproxy/envoy-alpine:v1.12.3
    container_name: envoy-api-grpc
    working_dir: /home/envoy
    command: /usr/local/bin/envoy -c /home/envoy/envoy.json
    ports:
      - 443:443
    volumes:
      - ./envoy:/home/envoy

  ##### redis
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
