version: "3.7"

services:
  user_db:
    image: postgres
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: user
      POSTGRES_DATABASE: user
    ports:
      - 5444:5444
